import PDFDocument from "pdfkit";
import QRCode from "qrcode";
import bwipjs from "bwip-js";
import { stateLabel } from "../constants/indianStates.js";

const TRANS_MODE = { 1: "Road", 2: "Rail", 3: "Air", 4: "Ship" };
const TXN_TYPE = {
  1: "Regular",
  2: "Bill To - Ship To",
  3: "Bill From - Dispatch From",
  4: "Combination",
};

function formatEwbNo(ewbNo) {
  const digits = String(ewbNo ?? "").replace(/\D/g, "");
  return digits.match(/.{1,4}/g)?.join(" ") || digits;
}

function placeLine(place, stateCode, pincode) {
  const state = stateLabel(stateCode);
  const pin = pincode ? `-${pincode}` : "";
  return [place, state ? `${state}${pin}` : ""].filter(Boolean).join(", ");
}

function supplyReason(bill) {
  const type = bill.supplyType === "O" ? "Outward" : bill.supplyType === "I" ? "Inward" : bill.supplyType || "";
  const sub = (bill.subSupplyType || "").trim();
  const labels = {
    1: "Supply",
    3: "Export",
    4: "Job Work",
    5: "For Own Use",
    8: "SKD/CKD",
    9: "Recipient Not Known",
    10: "Exhibition or Fairs",
    11: "Line Sales",
    12: "Recipient Not Known",
  };
  const subLabel = labels[sub] || sub;
  return [type, subLabel].filter(Boolean).join(" - ") || "—";
}

function hsnSummary(itemList = []) {
  if (!itemList.length) return "—";
  return itemList
    .map((item) => {
      const hsn = item.hsnCode ?? "";
      const desc = item.productDesc || item.productName || "";
      const qty = item.quantity != null ? ` - ${item.quantity}` : "";
      return `${hsn} ${desc}${qty}`.trim();
    })
    .join("\n");
}

function drawRow(doc, label, value, y, labelWidth = 140) {
  const valueWidth = 555 - 40 - labelWidth;
  const text = String(value ?? "—");

  doc.font("Helvetica-Bold").fontSize(9);
  const labelH = doc.heightOfString(label, { width: labelWidth });
  doc.font("Helvetica").fontSize(9);
  const valueH = doc.heightOfString(text, { width: valueWidth });
  const rowH = Math.max(labelH, valueH, 11) + 5;

  doc.font("Helvetica-Bold").fontSize(9).text(label, 40, y, { width: labelWidth });
  doc.font("Helvetica").fontSize(9).text(text, 40 + labelWidth, y, { width: valueWidth });

  return y + rowH;
}

async function generateBarcodePng(text) {
  return bwipjs.toBuffer({
    bcid: "code128",
    text: String(text).replace(/\s/g, ""),
    scale: 2,
    height: 12,
    includetext: false,
  });
}

async function generateQrPng(text) {
  return QRCode.toBuffer(text, { width: 120, margin: 1 });
}

export async function generateEwayBillPdf(bill) {
  const qrText = `EWB:${bill.ewbNo}`;
  const [qrPng, barcodePng] = await Promise.all([
    generateQrPng(qrText),
    generateBarcodePng(bill.ewbNo),
  ]);

  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: "A4", margin: 36 });
    const chunks = [];

    doc.on("data", (chunk) => chunks.push(chunk));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    doc.font("Helvetica-Bold").fontSize(16).text("e-Way Bill", { align: "center" });
    doc.image(qrPng, 460, 36, { width: 72, height: 72 });

    let y = 62;
    const validFrom = bill.ewayBillDate
      ? `${bill.ewayBillDate}${bill.actualDist ? ` [${bill.actualDist}Kms]` : ""}`
      : "—";

    y = drawRow(doc, "E-Way Bill No:", formatEwbNo(bill.ewbNo), y);
    y = drawRow(doc, "E-Way Bill Date:", bill.ewayBillDate || "—", y);
    y = drawRow(
      doc,
      "Generated By:",
      `${bill.userGstin || bill.fromGstin || ""} - ${bill.fromTrdName || ""}`.trim(),
      y
    );
    y = drawRow(doc, "Valid From:", validFrom, y);
    y = drawRow(doc, "Valid Until:", bill.validUpto || "—", y);
    if (bill.irn) y = drawRow(doc, "IRN:", bill.irn, y);
    y = drawRow(doc, "Portal:", bill.genMode || "1", y);

    y += 6;
    doc.moveTo(40, y).lineTo(555, y).stroke();
    y += 10;

    doc.font("Helvetica-Bold").fontSize(11).text("Part - A", 40, y);
    y += 18;

    const dispatchPlace = placeLine(
      bill.fromPlace,
      bill.fromStateCode,
      bill.fromPincode
    );
    const deliveryPlace = placeLine(bill.toPlace, bill.toStateCode, bill.toPincode);

    y = drawRow(
      doc,
      "GSTIN of Supplier",
      `${bill.fromGstin}, ${bill.fromTrdName || ""}`,
      y,
      155
    );
    y = drawRow(doc, "Place of Dispatch", dispatchPlace, y, 155);
    y = drawRow(
      doc,
      "GSTIN of Recipient",
      `${bill.toGstin}, ${bill.toTrdName || ""}`,
      y,
      155
    );
    y = drawRow(doc, "Place of Delivery", deliveryPlace, y, 155);
    y = drawRow(doc, "Document No.", bill.docNo || "—", y, 155);
    y = drawRow(doc, "Document Date", bill.docDate || "—", y, 155);
    y = drawRow(
      doc,
      "Transaction Type",
      TXN_TYPE[bill.transactionType] || String(bill.transactionType ?? "—"),
      y,
      155
    );
    y = drawRow(doc, "Value of Goods", bill.totInvValue ?? bill.totalValue ?? "—", y, 155);
    y = drawRow(doc, "HSN Code", hsnSummary(bill.itemList), y, 155);
    y = drawRow(doc, "Reason for Transportation", supplyReason(bill), y, 155);
    y = drawRow(
      doc,
      "Transporter",
      [bill.transporterId, bill.transporterName].filter(Boolean).join(" & ") || "—",
      y,
      155
    );

    y += 8;
    doc.moveTo(40, y).lineTo(555, y).stroke();
    y += 10;

    doc.font("Helvetica-Bold").fontSize(11).text("Part - B", 40, y);
    y += 14;

    const vehicles = bill.VehiclListDetails || bill.vehicleListDetails || [];
    const cols = [45, 95, 175, 255, 340, 400, 460, 510];
    const headers = [
      "Mode",
      "Vehicle / Trans Doc No & Dt.",
      "From",
      "Entered Date",
      "Entered By",
      "CEWB No.",
      "Multi Veh.",
      "Portal",
    ];

    doc.font("Helvetica-Bold").fontSize(7);
    headers.forEach((h, i) => {
      const x = cols[i];
      const w = (cols[i + 1] ?? 555) - x - 4;
      doc.text(h, x, y, { width: w, lineBreak: false });
    });
    y += 22;
    doc.moveTo(40, y - 4).lineTo(555, y - 4).stroke();

    doc.font("Helvetica").fontSize(7);
    if (!vehicles.length) {
      doc.text("No vehicle details", 40, y);
      y += 14;
    } else {
      for (const v of vehicles) {
        const mode = TRANS_MODE[v.transMode] || v.transMode || "";
        const vehLine = v.vehicleNo
          ? v.vehicleNo
          : [v.transDocNo, v.transDocDate].filter(Boolean).join(" & ") || "—";
        const row = [
          mode,
          vehLine,
          v.fromPlace || "—",
          v.enteredDate || "—",
          v.userGSTINTransin || "—",
          v.tripshtNo ? String(v.tripshtNo) : "—",
          v.groupNo && v.groupNo !== "0" ? v.groupNo : "—",
          v.updMode || "1",
        ];
        let rowH = 14;
        row.forEach((cell, i) => {
          const x = cols[i];
          const w = (cols[i + 1] ?? 555) - x - 4;
          const h = doc.heightOfString(String(cell), { width: w });
          rowH = Math.max(rowH, h + 4);
        });
        row.forEach((cell, i) => {
          const x = cols[i];
          const w = (cols[i + 1] ?? 555) - x - 4;
          doc.text(String(cell), x, y, { width: w });
        });
        y += rowH;
        if (y > 720) {
          doc.addPage();
          y = 40;
        }
      }
    }

    y += 16;
    if (y > 680) {
      doc.addPage();
      y = 40;
    }
    doc.image(barcodePng, 180, y, { width: 240, height: 40 });
    doc
      .font("Helvetica")
      .fontSize(10)
      .text(String(bill.ewbNo ?? "").replace(/\s/g, ""), 40, y + 48, {
        align: "center",
        width: 515,
      });

    doc.end();
  });
}
