export const STATE_NAMES = {
  1: "Jammu & Kashmir",
  2: "Himachal Pradesh",
  3: "Punjab",
  4: "Chandigarh",
  5: "Uttarakhand",
  6: "Haryana",
  7: "Delhi",
  8: "Rajasthan",
  9: "Uttar Pradesh",
  10: "Bihar",
  11: "Sikkim",
  12: "Arunachal Pradesh",
  13: "Nagaland",
  14: "Manipur",
  15: "Mizoram",
  16: "Tripura",
  17: "Meghalaya",
  18: "Assam",
  19: "West Bengal",
  20: "Jharkhand",
  21: "Odisha",
  22: "Chhattisgarh",
  23: "Madhya Pradesh",
  24: "Gujarat",
  25: "Daman & Diu",
  26: "Dadra & Nagar Haveli",
  27: "Maharashtra",
  28: "Andhra Pradesh",
  29: "Karnataka",
  30: "Goa",
  31: "Lakshadweep",
  32: "Kerala",
  33: "Tamil Nadu",
  34: "Puducherry",
  35: "Andaman & Nicobar",
  36: "Telangana",
  37: "Andhra Pradesh (New)",
};

export function stateLabel(code) {
  if (code == null || code === "") return "";
  return STATE_NAMES[Number(code)] || `State ${code}`;
}
